# Generated by Django 4.1.3 on 2022-11-20 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CSVModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=25500)),
                ('name', models.CharField(blank=True, max_length=25500)),
                ('lvl1', models.CharField(blank=True, max_length=25500)),
                ('lvl2', models.CharField(blank=True, max_length=25500)),
                ('lvl3', models.CharField(blank=True, max_length=25500)),
                ('price', models.CharField(blank=True, max_length=25500)),
                ('priceSP', models.CharField(blank=True, max_length=25500)),
                ('amount', models.CharField(blank=True, max_length=25500)),
                ('propertyFields', models.CharField(blank=True, max_length=25500)),
                ('purchases', models.CharField(blank=True, max_length=25500)),
                ('unit', models.CharField(blank=True, max_length=25500)),
                ('img', models.CharField(blank=True, max_length=25500)),
                ('onGeneral', models.CharField(blank=True, max_length=25500)),
                ('description', models.CharField(blank=True, max_length=25500)),
            ],
        ),
    ]
