# Generated by Django 4.1.3 on 2022-11-25 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_uploadcsv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csvmodel',
            name='amount',
            field=models.CharField(blank=True, max_length=25500),
        ),
        migrations.AlterField(
            model_name='csvmodel',
            name='code',
            field=models.CharField(blank=True, max_length=25500),
        ),
        migrations.AlterField(
            model_name='csvmodel',
            name='description',
            field=models.CharField(blank=True, max_length=25500),
        ),
        migrations.AlterField(
            model_name='csvmodel',
            name='img',
            field=models.CharField(blank=True, max_length=25500),
        ),
        migrations.AlterField(
            model_name='csvmodel',
            name='lvl1',
            field=models.CharField(blank=True, max_length=25500),
        ),
        migrations.AlterField(
            model_name='csvmodel',
            name='lvl2',
            field=models.CharField(blank=True, max_length=25500),
        ),
        migrations.AlterField(
            model_name='csvmodel',
            name='lvl3',
            field=models.CharField(blank=True, max_length=25500),
        ),
        migrations.AlterField(
            model_name='csvmodel',
            name='name',
            field=models.CharField(blank=True, max_length=25500),
        ),
        migrations.AlterField(
            model_name='csvmodel',
            name='onGeneral',
            field=models.CharField(blank=True, max_length=25500),
        ),
        migrations.AlterField(
            model_name='csvmodel',
            name='price',
            field=models.CharField(blank=True, max_length=25500),
        ),
        migrations.AlterField(
            model_name='csvmodel',
            name='priceSP',
            field=models.CharField(blank=True, max_length=25500),
        ),
        migrations.AlterField(
            model_name='csvmodel',
            name='propertyFields',
            field=models.CharField(blank=True, max_length=25500),
        ),
        migrations.AlterField(
            model_name='csvmodel',
            name='purchases',
            field=models.CharField(blank=True, max_length=25500),
        ),
        migrations.AlterField(
            model_name='csvmodel',
            name='unit',
            field=models.CharField(blank=True, max_length=25500),
        ),
    ]
